project:
  type: website
  output-dir: _site
  render:
    - data-tech-poli-arch.qmd
    - slides/slides.qmd

website:
  index-page: data-tech-poli-arch.qmd
  sidebar: false
  navbar: false
  format-links: 
    - pdf
    - text: Slides
      icon: easel
      href: _output/slides/slides.html