project:
  type: default
  render:
    - "*.qmd"
    - "!notes/"
    - "!guidelines/"
    - "!logistics/"

bibliography: assets/data-tech-poli-arch.bib
csl: assets/chicago-author-date.csl

filters:
  - abstract-section
  - assets/count-para.lua