project:
  type: website
  output-dir: _site
  render:
    - data-tech-poli-arch.qmd
    - slides/slides.qmd

website:
  sidebar: false
  navbar: false

project-metadata:
  data-tech-poli-arch.qmd:
    format:
      html:
        output-file: "index.html"

  website:
    format-links: 
      - pdf
      - text: Slides
        icon: easel
        href: slides/slides.html