project:
  type: website
  output-dir: _output/html

website:
  title: "Data Management is People Management"
  sidebar: false
  navbar: false
  page-navigation: false

render:
  - data-tech-poli-arch.qmd

project-metadata:
  index: data-tech-poli-arch.qmd