project:
  output-dir: _site/slides
  render: 
    - slides/slides.qmd

format:
  revealjs:
    slides: true
    output-file: slides
    embed-resources: true
    toc: false
    theme: black
    slide-number: c/t
    template-partials:
      - slides/title-slide.html
    css: slides/slides-styles.css
