# Discussion
Throughout all of these observations there is a clear tension between the need to present information using formal data structures and their failure to fully capture archaeological understanding.
On one end, archaeologists are pressed to fulfill their scientific mandate by ensuring that the outcomes of their effort are and appears to be decisive, consistent and stable --- qualities that instill confidence in the evidentiary character of data.
At the same time, archaeologists struggle to make their data fit a standard mold.
This tension produces an "epistemic anxiety" whereby archaeologists recognize --- and fail to reconcile --- discrepancies between their commitments to formal scientific standards and their intuitive understanding of the limits of this approach to knowledge-building [@huggett2022].

To escape this anxiety, archaeologists have established workflows that offload decision-making to people who are not immediately present at the site of archaeological encounters [@batist2025; @batist2025a].
By re-casting archaeological encounters as a series of programmatic operations and decision-trees, database managers and project managers claim creative agency over how to represent archaeological objects.
This removes the burden of decision from the moment of the archaeological encounter, and re-casts those who record what they see, feel, smell and hear as devices that simply match their sensory experience to predefined criteria provided to them.
Put another way, workflows downplay interpretive potential at locus of the archaeological encounter by forcing adherence to a series of pre-digested decisions and by presenting anything other than the outcomes of those decisions as unnecessary addenda to the true or official archaeological record [@batist2024a].

However, while workflows are ways of coping with the epistemic anxiety, the tension that produces it is an ever-present aspect of archaeological (and scientific) research.
In fact, the workflows are constantly being tested and resisted for two reasons. First, archaeological objects and phenomena are "wild" in the sense that they were not made for the benefit of archaeological understanding. And second, the eclectic, improvised, opportunistic and nimble nature of archaeological knowledge production resists any urge to impose standards; this inability to fully control archaeological practice is not due to intentional acts of rebellion, but is rather born out of necessity to respond to the slippery and inconsistent character of archaeological encounters.

This paper noted how the persistent challenges to archaeological workflows, specifically through relationships between people occupying different roles and the formal data management system.
Specifically, I noted how members of archaeological projects were recruited to either represent the interests of the database or the of the things to be recorded by it.

For example, in the situation of finds processing, trench supervisors were responsible for ensuring that the materials were channelled into discrete buckets, in accordance with the broader pipeline in which excavation is situated.
[Something about cleaning.]{.mark}

Then, when analyzing the finds, the lithics specialist relied on her extensive training to systematically classify the materials, while her assistant served as the database's enforcer.
For both of them, the database was an immutable entity that they were forced to conform to.
However, when the consultant was called in, they were free to make changes to the schema.
And it was then up to the primary lithics specialist to update the data model with those new considerations, and to re-formalize them into a new authoritative data structure.

The amazing thing is that despite these challenges and tensions, archaeologists were still able to generate meaningful insights about the past.
They accomplished this by developing ways to easily navigate between tight and loose control; on the one hand, confident representations of archaeological encounters are deemed especially valuable for producing scientific outputs, but this is tempered by a common understanding that that approach is a limited window upon which we may view the past.
This flexibility to think of both the potential productive outcomes and limitations of different forms of engagement enables us to understand when it's possible to bend the rules, when we need to account for context, when we need to be more structured.^[It is notable that data scientists prefer to work with little understanding of how data came to be. Their power derives from their ability to take data at face value, and for that to be considered a valuable quality. Archaeologists also have people who deal with data, but we call them archaeologists since they are part of our community of practice and have obtained this archaeological sensibility through fieldwork and other embodied experiences.]
Moreover, the capability to actually enact this flexibility derives from social and communications strategies, rather than purely technical solutions.
This understanding, which is embedded in our social and collaborative relations, rather than in any technical apparatus, is what makes it all work, somehow!
