# Conclusion
This paper frames the technologies that archaeologists use to re-situate individual archaeologists in relation to project collectives as means through which managerial protocols are carried out.
Specifically, it documents how systems designed to direct the flow of information do so via the coordination of labour, and the strategic arrangement of human and object agency.

All acts of recording requires the capability to make decisions, but the nature of these decisions changes depending on distance from the archaeological encounter.

Practically speaking, archaeological records are created through human intervention, whereby people ascribe meanings to materials, delineate natural phenomena from cultural processes, distinguish signs of modern intervention from activities performed by the archaeological other, and select signal from noise.
And as with all things of anthropogenic origin, the records that archaeological produce carry with them traces of the extended social and material worlds that scaffold the communities that produced them.

Workflows are _attempts_ at making data fully transmissible and interchangeable, which are resisted by the slippery nature of the things we attempt to document and the myriad ways in which archaeologists attempt to capture them.
These gaps, frictions and sources of resistance need to be more fullly accounted for in philosophies that underpin data management infrastructures and policy frameworks --- which are ultimately mechanisms of control --- in order to ensure that these services actually serve archaeological needs, values, expectations and priorities.
If we are going to attempt to extract meaning from the traces of the archaeological past, we need to be realistic about what this actually entails.
