# Supplementary Materials
This supplement contains sections of transcribed interviews referenced throughout the paper.
References are ordered by case and by the order in which they appear. Each reference has a prefix corresponding with the case to which it pertains.

## Case A
##### A1 {#sec-A1}
**Zack:** So my first question is, do you see fieldwork as being somewhat distinct? How do you separate the different research environments you work in? Like field work, and then lab work, and then other work? How to they relate to the overall professional...\
**Basil:** Umm, I would like it to be as integrated as possible. Obviously there is the real pragmatic, the field is here, the labs are there. I'm not so used to talking about uhh, Pinnacle Point, in South Africa, where they actually have an OSL lab on site, they're doing this stuff on site. You know, I'm not, I don't think about that in terms of like ooh, that would be lovely, but what I do desire, and this is where it becomes a bit difficult and where some frustrations for me come in, is like, I want the people who are going to be doing the lab work to be as engaged in possible in the field. So that's why it makes me very happy that we have someone like Marie, who is going to be doing our OSL dating over in [her lab at her home institution], coming to the site, doing the sampling, discussing in detail the archaeology with knowledgeable characters such as Gabe, Alfred, Liane, because it makes me feel so much more confident that the results we're gonna get are trustworthy. Now, if push came to shove, I'm sure that Alfred, Gabe, Liane will be able to take those samples to the standards required by Marie, send them to the lab, and Marie would be able to process them. Indeed, that's exactly what we did with out first, umm, set of OSL dates. We took the samples, and we sent them off to Clifford, who until last year, umm I'd never met. Umm, and and, you know, that kind of umm lab based work is fairly standard for archaeology. You take a sample, you send it off to do something, but as much as possible, I want those people involved to be at the site so they understand the questions we're asking, they really understand the archaeology, and that will help them umm fine tune their sampling, their comprehension of what they're engaging with, so it's very important for me to have, you know, in theory Melinda from [redacted] is doing the archaeobotany, but she's given us her PhD student, Dorothy. Well Dorothy is there, she's seen the archaeology, she's working with us, you know, so there's a greater degree of comprehension. I really wanted a woman called umm Rachel this year to come down and look at our, our charcoal material, and in the end she couldn't umm come, uhh I saw her in [redacted], we're gonna try to move the material to umm the [redacted] Lab in [redacted] for her to work on. And for me that's a bit of a disappointment. You know, it was always going to happen sooner or later, there was gonna be somebody who couldn't come, or who didn't see it as necessary as actually coming, we'll look at this material, in a completely isolated manner, you know. And I'm sure Rachel has done fabulous work on carbon from Palaeolithic and Mesolithic sites elsewhere in the [region], she is exactly the person to work with, but I find it a bit sad maybe there will be a slightly lesser impact, because you know, she's never even been to the site. Yes, we can give her text, we can give her photos, we can give her videos, but it's, for me, umm there there's that kind of real, you know, the reality, the actual being there. I, I, I feel, I believe, I would like to think, umm, it gives the scholar an extra...\
**Zack:** I mean, can you be a bit more specific though, when you think about that being there, like, what that really entails, like how that really is truly beneficial?\
**Basil:** Well, I think, you know, it, it was great pleasure to you know, sit back across the table and watch, listen to Marie and Gabe and Alfred really talking in great detail about what they thought was going on in the site formation processes, what implications that had for sampling, what implications it had for the interpretative limitations of what they can say, and how things could be bracketed, how things could be rescued. They were already working on the narrative, they were like, it was basically, they were ready to roll with whatever we got. You know, it wasn't a matter of like "this is the result, ooh now what might this mean?", they were like really thinking through what this sort or, where this might actually take us, and they were all, they were using the same language, they really, there was a great deal of mutual comprehension. Umm, now, you know, in terms of the site, if we sent the stuff off to umm Marie, she would have generated the same dates, but there there would be, you know, I, with with Clifford and and the University of [redacted] there's been a bazillion emails, I mean part of this is pragmatic, in terms of like a bazillion emails back and forth, and not quite comprehension, you know "oh sorry, I didn't realize that this sample came from this", like you know. Umm, so. And I think also, maybe part of this is like, you know, Marie is now invested, she's part of the team, she's part of the community, hopefully she'll have a feeling of, you know when push comes to shove maybe she'll just take it a bit further, because she's, she has an investment with it. Whereas like Rachel, eh, this is the latest dataset to pass across her desk, yes, you know I've got an obligation, but maybe it's more of an obligation rather than an investment. You know, so it's, it's, it's being part of a community of scholars by actually coming and joining us. So you know, we have a personal relationship, Rachel and me, but Rachel hasn't met and talked with Dorothy, Dorothy has separated the samples for Rachel, Dorothy umm, Rachel, if she does the work in the [redacted] Lab will be able to engage with Alfred who will be there at the same time, so there is a bit of a disconnect. So it's not a complete disaster, but I feel, you know, part of this is wanting to be invested in the project.

##### A2 {#sec-A2}
Moreover, Marie wanted to come to site to sit down and go over the OSL results with Basil and Gabe and Alfred, to explain the results and dispel any potential misunderstanding. Meanwhile, Basil and Alfred were very nervous with anticipation, and in some car ride discussions talked about how they would write to her to find out more before her arrival. They were concerned with guiding the geoarchaeological interpretations of the landscape to decide how to prioritize the excavation of the site, and to guide Jolene in her interpretations of the lithics.\
Marie, and a few others, have now left to take more samples, which must be done at night, out of the sunlight. She is also here for that more practical reason.

##### A3 {#sec-A3}
Trench [redacted trench ID] and [redacted trench ID] have been un-backfilled yesterday for the sampling and the need to retrieve OSL dosimeters from their sections.

##### A4 {#sec-A4}
Without cleaning, and perhaps just to see whether it is worth her time, or to check if the deepest spot she reached is adequate, she measures another elevation; she can then go down to that point knowing that it works.\
Actually, it was to measure the depth of a large handaxe-looking thing. She noted it earlier but I guess she waited till her legs got sore to take an elevation. I may ask later.\
She did not use the term x find. She is unfamiliar with handaxes, [illegible] particular a preform, but apparently Basil got excited about one on the other side yesterday, and because she's a newbie she decided to record it just in case.\
A few minutes later Olivia uncovered a large phallus shaped stone, similar in size to the large handaxe, and we all joked around about it.\
Nina at the sieve, brought over an orangey-brown piece of chert, no cortex, for Olivia to examine more closely. "If it weren't this colour, it might be shitty material. I would chuck it. But so [illegible] heat treatment caused darkening colour so this might be that."

##### A5 {#sec-A5}
At around 7:55 Will asks me to put a little nodule in the soil sample bag. I may ask him about that later.

##### A6 {#sec-A6}
Jolene separating diagnostics from non-diagnostics. Non-diagnostics get pulled aside to Agatha's side of the table, where she separates those into ecofacts/natural/too weathered to matter. She throws those in a zimble, and counts them off. This is counted, and subtracted from the number recorded the other day, in error, which included both natural and cultural together.

##### A7 {#sec-A7}
**Jolene:** Yeah because you can't study dirty lithics\
**Agatha:** I mean that's also connected with the schedule, we changed the schedule of the new place we worked and we are supposed to stay there until five\
**Zack:** What do you mean by the dirty lithics?\
**Agatha:** Well the lithics came dirty again\
**Jolene:** They're not washing them properly, so how can you make something\
**Zack:** Do they get better as time goes on?\
**Agatha:** Yeah, but I mean the thing is like no one is thorough enough to empty the bag from the soil, and then put the washed lithics inside, and no one is there to actually control the, because we have a new schedule so I mean we put some people in charge but...\
**Zack:** Pardon my sort of half-feigned ignorance for the sake of the interview, what does dirty lithics, what are the problems that they cause?\
**Jolene:** Well you can't study them\
**Agatha:** You can't see anything\
**Jolene:** They bring them to the lab and you're supposed to look at them as say this is you know, i dunno\
**Agatha:** Sometimes even when they're washed properly and the raw material is a bit like, we're not used to that raw material, it's hard to see the ridges and everything, but like even if they're not washed properly then that's another headache.\
**Jolene:** It stops us from doing our, so we need to do their work\
**Agatha:** The worst was like talking with Denise and trying to pursue like what is re-touched and what's not, and Jolene was like pushing one small piece saying like this is retouched, and they were like no it's not, and then I just went and wash it and there was a completely fresh, it was white haha and it was retouched I think, it sucks.\
**Zack:** But did she think it was retouched?\
**Jolene:** Yeah\
**Agatha:** Yeah

##### A8 {#sec-A8}
Moved to watch Agatha now. She pulls a pile from the larger pile made by Jolene. Separates cultural material from natural material to throw away. Cultural material is out in a pile in the back, natural is kept where it is, directly in front of her. Once the pile in front of her has no cultural material in it anymore, she separates the natural to the side and clicks her clicker according to how many are moved. Then she sweeps these off the table, into the zimble on the floor. Or, to be quicker, she clicks as she drags them into the zimble, or as she drops them in after grabbing a handful of small material. This number will then be subtracted from the total count, which was mistakenly recorded earlier without removing the natural materials.

##### A9 {#sec-A9}
Jolene describing laid out materials. Somewhat of a performance. Starts with a big core from Lauren's trench. It stands alone. Tosses is around, across her hands, but looks at Agatha, who takes dictated notes, as she speaks. Speaks a few words at a time, [illegible] so that each four words are enunciated for Agatha.\
Concludes by "and that's it" before adding a last minute additional note. Then adds "and that's enough".\
Onto [redacted context ID], laid out already. Looks down at the table, scans the material. Does not touch yet. Generalized descriptions. Most, many, boolean logic, etc. Describes a few particular objects in more details. Hones down into more specific groups of finds, describes tendencies among them.\
Still very descriptive. Stating how many of what. Defining the scope of the assemblage. Not yet uttered anything about periods, etc [illegible]. After describing patina, however, she begins to add some interpretations of deposition conditions. Then notes burned pieces. Now explicitly notes "concerning dating of material..."\
Notes caveat first, conditional clause proceeding what her observations are pertaining to a subset of the material, very cautious and selective with her words, and does not backtrack or correct herself.\
Then explicitly introduces her notes on the emery.\
Then moves to the side, has closer look at the smaller finds. Physically handles a few.\
Lydia asks to put them back in the bag. Jolene says sure, but goes through them, selecting a few to bag separately, for [illegible] to go through later for a second, more specific look.\
Lydia's question to pack up was a welcomed interruption. Jolene was a bit fed up with this context, since it has been on the table for a very long time and she was glad to see it settled.\
Agatha writes down what Jolene dictates in a small notebook. She will then transfer these descriptive notes to the database in a more standardized and "nicer" language.\
Now for [redacted context ID]. Starts with material selection. Most to least. Notes mixed material, based on partial and "[illegible] typological [illegible]", does not specify yet.\
Now describes Mesolithic. Describes most abundant [illegible] of lithics. "As well as one multidirectional core", it stands out as exceptional.\
"Second group would be Upper Pal tools and blades in similar preservation". Then goes on to describe subgroups within it. "This assemblage is defined by..."\
Then moves on to Lower Pal, as well. Grouping emphasizes patination, since this is important for discerning Lower Pal material.

##### A10 {#sec-A10}
She actually really hates these organizational tasks. She is really grateful for having Agatha as her assistant, who could do all of that, which she generalizes and dismisses as of somewhat lesser importance, or as the distractions from her more hands on work.

##### A11 {#sec-A11}
Agatha does a lot of busy work. She brings material back and forth from storage, for Iona to count and weigh, and for Ana to analyze. She also prepares level 1 recording sheets where counts/weights can be written down officially. Also compiles the list of already closed contexts, numbers of bags within, etc. Planning work for [illegible].

##### A12 {#sec-A12}
**Basil:** We're still, I always sort of gave, because Jolene's been here from the get-go she has sort of first dibs on what sort of material she wants to work on, and I think she was always keen to work on sort of Middle to Lower, but until this year we didn't really have much of that. Now that's crystallizing a bit more for her, whereby it makes sense for me to bring in somebody else to work with me on the Upper Palaeolithic or Mesolithic.

##### A13 {#sec-A13}
It is extremely difficult to share how good I feel about this code. It represents a major breakthrough in my learning how to use R, and it sucks that no tangible research products can come out of this in a way that shows my skills. I actually included an R script on my [funding] application that was due on Friday, as a non-refereed contribution, but that designation is sketchy.\
This seems to be true of database work in general. I will likely not be published on major papers as a co-author because my work is `supportive' but not necessarily "creative". The output of database work is other people's work. But the product, the database itself, is a creative output. It's the result of a tremendous amount of unpaid work, highly skilled work at that. However, there are no ways to recognize or evaluate these skills. At least not in a formal or bureaucratic way. Perhaps this is why there is so much gatekeeping and nerd-signaling among "digital archaeologists", it's a way to indicate that one's in the know. But I don't believe that that is a reliable indicator of skill or know-how, it's easy to play the game on twitter, it takes lots of time, over the long term, to develop digital skills.

##### A14 {#sec-A14}
**Zack:** Are you including any supportive documentation, such as data tables, figures, details, methodological descriptions or metadata?\
**Basil:** Yes. So umm if it's finally accepted, it will be in the journal Science Advances, which has umm, it was, in the end it was about an 8000 word limit, uhh which I think, it's fairly short. I mean originally when we wrote it, we wrote it for Nature, umm which was like a 1500 word article. Umm so... which is like very concise. Umm, now, with all of those venues, you know, it's more and more common that people obviously are reading stuff online, all of these venues, including Science Advances, should they ultimately publish it, umm we, they facilitate and encourage the publication of supplementary online material. So to an extent that's where you can give a little, you know, a certain amount of data dumping. Umm, where you can go into the really nerdy-- and in a way it's great in terms of like, you know, your main article, it's a relatively flowing piece of narrative. And then, you know, see supplementary online materials for a detailed breakdown of the stratigraphy, for a more detailed discussion of the lithics, for a more detailed breakdown-- actually no, at the end of the paper you're then allowed a materials and methods thing, which is where you go into great detail for the scientific umm uhh audience, uhh the nature of our dating techniques, et cetera. So, quite snappy archaeological big picture narrative, expected materials and methods for the, sort of, the main paper, and then supplementary online materials, that's where you can go, you know, you can write hundreds of pages. Umm, there is an expectation... so, this is an open access journal, umm.\
**Zack:** Entirely?\
**Basil:** Yes.\
**Zack:** Not a hybrid or...\
**Basil:** The Science Advances one is open access, which if we're accepted will cost us 4500 dollars US, and one of the things they ask us... so, each author is expected to sign a quite detailed form that I've not hitherto dealt with before, which basically gets you to stipulate quite clearly what your contribution was in the paper. So at the end of the paper is says, you know, use your initials, [redacted] for myself, umm director of the project, I kinds worked on the lithics, co-wrote the paper, and then you know, other people, geoarchaeology, blah blah blah, and et cetera. But then we also, online, have to sign these documents, in terms of, you know, did you produce any algorithms? Yes, no. Umm did you, were you the person who raised the main funds? All these projects, in great detail. Umm.\
**Zack:** What do you think the value of that is?\
**Basil:** Umm, given that it's... I'm not entirely sure why we had to do it. I'm sure there was some kind of blurb, which, you know, it's one of these things that you have to say oh I accept, you have to do it, as opposed to really ponder it. Umm, that I don't think is published, so whether there's, who evaluates that, I'm not quite sure, or it's exact purpose. I mean there is a slight discomfort, potentially, in that one of the authors is essentially a political appointee that we know has to be included, umm and I'm not quite sure where on that long yes/no list they would have hit yes. I don't know if that would then trip anything from the journal in terms of like he can't be involved, you have to have written something or given something. Umm, but yeah. So, but umm one of the other things they said, is you have to be crystal clear in terms of you have to provide your primary data that supports your arguments. Or, and we took the or route, because we're still organizing our data to be in a umm, a more accessible format, umm or basically you say it will be made available should you contact us. So we've, we've included that required statement. If anybody wants, you know the uhh, the numerical data that underpins any of this stuff then we will happily hand it over.

##### A15 {#sec-A15}
**Zack:** Umm, have you worked in other settings? Like you've worked in the museum, right? Just lifting boxes, right?\
**Jane:** Yeah. But...\
**Zack:** Yeah. And you've just been in the field I guess, right?\
**Ben:** I've been in the museum twice. I've lifted boxes like Jane. I've also done the counting and a bit of lithics washing in the museum.\
**Zack:** What did you think of it?\
**Ben:** Umm, you wanna go first?\
**Jane:** Not my fave, to be honest.\
**Zack:** Yeah.\
**Jane:** I just, like, I don't... maybe if I knew more about what I was looking at then I would be more interested. Like I'm sure if it was like a bone lab I would love it. But it just like, lithics are cool but they're not really my jam and I don't really know what I'm talking about, so like, working with them is kind of like, it's like counting rocks. You're required to count like scapulas and unclear\
**Ben:** Yeah. I was basically the same way. I found it interesting at first for a little bit, and then it just became monotonous and like boring and just mind-numbing, basically. And the thing you said about, just, you don't have the expertise in it, I felt the same way. Like I was just looking at lithics or rocks that I would have picked out, and I can't say like, oh this one is definitely not. So I'd be like, oh, Agatha, is this something?\
**Zack:** I actually haven't taken a lithics class yet, or at all.\
**Ben:** Well I'm planning to next semester, next year, but I had to--\
**Zack:** Was it because of this project, or no?\
**Ben:** Yeah, basically. No no, it was, for sure. It was because Basil, and I have some experience with it so I'm gonna do better, hopefully.\
**Jane:** Hahahaha\
**Ben:** In theory.

##### A16 {#sec-A16}
**Zack:** Uhh in your view, what are the main challenges or considerations in managing information productively for archaeological... can you just mentioned an aspect of that?\
**Basil:** Sorry, managing...?\
**Zack:** For managing information.\
**Basil:** Umm\
**Zack:** In archaeological, which may involve fieldwork or other aspects of work.\
**Basil:** Umm, it's, part of it is actually sort of umm, a combination of trust and communication, and occasionally a bit of coercion. There's, my particular role is to like, you know, you let certain people, you're bringing people who you believe, or know, can do their job, and that job is often the generation of data that's pertinent to answering your research questions. Umm, and different people work in different ways. Some people are very gregarious, other people are like hyper paranoid about keeping stuff, and you just gotta, you know, as long as there are deadlines and you need communicate how you're gonna need the data, which again, that's a steep learning curve, often at times you just assume that by osmosis somebody is gonna know what you're gonna want by the end. Umm, and you know. And now I'm coming to appreciate that, you know, there's a greater degree of me being hands on and centralized, and it's like guys, everybody has to work in this particular system. You know, your end products will need to be coded and accessible in this particular way. How do you get to generating those data? That's your skillset, how you work, fast, slow, you know, et cetera. That's up to you. But ultimately we're gonna need an artefact ID system. However you deal with your pottery otherwise, or your ceramics or your ground stone, you are going to need to interact with this point. Umm, and, you know, this is a new project, a number of us are young scholars who-- yes, we've all worked on other projects, but you know, more often than not those projects have their own systems, so it's a matter of like, you know, figuring out, you know, what we need. And some of this is probably gonna be question-led. Other parts of it is just like no, this is just, this is what everybody does. And other parts of it might be from external forces. You know, it would be the, the [national] Ministry of Culture requires us to provide an inventory of our crates.

##### A17 {#sec-A17}
**Basil:** and where you tend to have the umm, I mean there's, in terms of mediation, there's mediation in terms of like, Zack, I need you and Dorothy to get together so that Dorothy's skills and data dovetail and is integrated into the database. So that's like okay, I recognize an issue, lets make the space for this to happen, and try and mediate and then okay I think you guys are bright enough to talk to each other, and then you can come back to me in terms of like do you want this or do you want that.

##### A18 {#sec-A18}
**Zack:** So how do you get ramped up again?\
**Basil:** Umm, usually umm the energy comes externally, or I use external pressures to get me back up and running. It's like, oh, I've got 15 days to submit the next grant application, which with a number of our funding agencies involves writing what we did last year, you know, how did you use your budget, what did you achieve? Umm, so umm, and also the fieldwork committee at the [redacted] Institute. There are, there are two or three sort of umm deadlines coming up, that then kick me back into it, which is going to be a matter of like, okay oomph, now I'm going to have to need to send an email to Alfred, please can you send that photograph, Alfred can you explain what you mean by this, Alfred can you write your report up. You know I got yours ahead of time, I've got your database report. Dorothy has sent through her report, but her report is not very interpretive.

##### A19 {#sec-A19}
**Zack:** So, moving on maybe to some more uhh, the aspect of data sharing in general, umm how involved were you in the uhh preparation of data that will be shared openly? I mean, obviously it's still in uhh processed, you said that you would have that contact us for uhh... Like, who is it, is it Gabe or, like who is going to be doing that, and how do you anticipate that being, that going on?\
**Basil:** Well the umm, the, there's two main, umm three main sets of data in this. There's the geoarchaeological data, umm which, hopefully we have made accessible. Everything that the public or the readership needs. Umm, there is a slight tempering of all of this in that these data underpin a yet to be completed PhD by Alfred.\
**Zack:** Right.\
**Basil:** Umm. The analysis of the lithics, which is undertaken a level 1 and a level 2, is primarily uhh, if not exclusively undertaken by Jolene and myself. Those data are then fed into a database, which means by extent you and others have immediate access to it. Gabe often then runs with those numbers and does a lot of, sort of, you know, what can we tease out of this patterning-wise, you know. Usually it's a matter of, like, Jolene and I are very much focused on the description of the assemblage, and we generate these data that somebody like Gabe can then sort of interrogate in terms of assemblage structure and correlations, and whatever umm.\
**Zack:** How does that relate to the geoarchaeological? Does it link up in any way?\
**Basil:** Umm, no. Hahaha. So, you know, again, it's, I'm painfully aware of the nature of Alfred's work, in that he's a young scholar who needs a bit more control over his data than somebody like myself. Umm, so, you know, he sent, you know, Alfred's been very good in terms of, he's always been on time or up front in terms sharing data, interpretations, be that photo micrographs, be that maps, be that text, be that quantification, qualification of whatever it is he's doing. Umm, but in terms of the original counts, or all of the various versions of the photo micrographs that he took before he chose version seven, those I don't have to access to, and nor have I asked him to hand it over yet. Umm, because I feel, you know, his rights, in that instance, kind of trump that of the project.\
**Basil:** Umm, so umm, the number crunching that go, you know, the, a whole bunch of the smoke and mirrors that underpins umm the French dating people, you know, we have all the end products, but, you know, the algorithms, the 17 excel files that have been played around with, or whatever it is they do in France, I don't have those. And to be honest, my mind doesn't even work in that fashion, in terms of I need the archive, I need to be able to see every stage in it. Because if they gave it to me it's gonna cluster up my computer and I wouldn't know what to do with it in the first place.\
**Zack:** But what has the publication done with it?\
**Basil:** Umm, like I said, Science Advances requires that we make available, make data available, umm primary data available or make, have a commitment to sharing it should somebody ask for it.

##### A20 {#sec-A20}
**Zack:** I noticed one example I found really fascinating was your conversation, your three way conversation with you, Alfred and Andreas, I found that really fascinating as you all seemed to have a different role in the conversation. I was wondering if you have any strategies that you commonly use, to assess whether they're different, or whether they're integrating or whether they're divergent, or like, how do you sort of assemble these different ideas, and these different knowledge bases?\
**Basil:** I mean, either I initiate meetings or I make sure that, you know, the three people who need to be talking to each other are brought together. I mean what was fantastic last year was having brought in Marie, Marie, Gabe and Alfred spoke the same language, it was wonderful to see. Whereby I was like, after a while, okay, I'm going to go off and talk to these people over here, you guys are obviously perfectly capable on your own.

##### A21 {#sec-A21}
**Basil:** Well, I think, you know, it, it was great pleasure to you know, sit back across the table and watch, listen to Marie and Gabe and Alfred really talking in great detail about what they thought was going on in the site formation processes, what implications that had for sampling, what implications it had for the interpretative limitations of what they can say, and how things could be bracketed, how things could be rescued. They were already working on the narrative, they were like, it was basically, they were ready to roll with whatever we got. You know, it wasn't a matter of like "this is the result, ooh now what might this mean?", they were like really thinking through what this sort or, where this might actually take us, and they were all, they were using the same language, they really, there was a great deal of mutual comprehension.

##### A22 {#sec-A22}
**Basil:** Andreas did the micromorph of the block that was taken from the cave. He confirmed that all the material was basically wash. Our fear was that like, rather than digging stuff that was in the cave— because originally we thought that it was, you know, it was completely sealed, and by extent anything from inside the cave was deposited in the cave. Then in fact it turns out that really the cave is a false cave because it's, you know, a little crevice umm and some rocks had broken off and capped it but there's still some gaps, and stuff has squeezed through toothpaste-like and created this whatever. But then apparently within this matrix was soil that had been displaced from higher up the hill of a type that is not to be found anywhere on the hill anymore and is some of the oldest material we've come across. What significant that is, I do not know, because he slightly confused me.

##### A23 {#sec-A23}
**Basil:** And so also in terms of like, you know, we have the feature sheet, which would be used much more regularly I think in a British or a more normal [local] excavation, whereas like we have, you know, the one yet to be defined hearth complex, which I mean, one has to be careful about, and I'm just thinking about that today, you know, Andreas has emphasized that, you know, the hearth are in fact hundreds of firing events. So bundling that together as a feature, you know, one has to be wary about what that represents.

##### A24 {#sec-A24}
Andreas tells a very nice monologue narrative to relay his interpretation. Alfred, and Basil, relate their experiences and the collections of [the project], to Andreas, trying to see how the narrative can be leveraged and how they can contribute developing and refining the narrative.\
They together explore potential streams that might be followed. Seems like a negotiation of sorts.\
Alfred proposes a possibility.\
Andreas evaluates its viability and potential to be integrated within the current narrative.\
Basil relates similar efforts that have already been made, tempers the exploratory drive, and offers a pragmatic, project-oriented perspective.\
Basil is standing still and observing conversation between Alfred and Andreas. Does not contribute, except to interject once in a while. Difficult to mind read, but seems that he is evaluating the comfort and expertise among the two others, evaluating how certain they seem.

##### A25 {#sec-A25}
**Andreas:** So, in the sequence here, see if you take, first of all the lower half with the clay, is certainly a long, the result of a long activity phase, weathering, transformation. Now that I see it more clearly, it appears in several places. It's a kind of uhh, an environment that, because it's [unclear] clay, sometimes it retains water. So it's a kind of, not exactly stagnant, but you can cal it something umm... but during the wet season it can be quite muddy or something like that. Now that I see it here it looks like being at the expense of any real [...]. This one is probably weathering, and down to, so this is something like the clay that you see at the bottom. I'm talking about a lot of time here. Okay, this is tens o thousands of years at least. Heh. I'm not a show-y person but I think the muddying, in order to [...] alteration of the bedrocks, this is old stuff. Uhh, then here you have the co-variation and some sand blown in. And on this side, on this side, is the, the fire base , sand, sand right below the, the hearth. The blown sand of, by the base, sand. This was, now the sand that, the sand that was actually related, you had, you had probably a stable formed, some kind of small weathering of the sand [...], it could be aeolian. It has to be aeolian. I can only imagine the processes that brought here [pure sand]. This sand is de-calcified, which again implies kind of, some kind [left on] the surface in order to de-calcify. And on this surface, the guys came and put fire. Actually the matrix of the black stuff is sand again. I was surprised when I saw it but it's, like if I saw you tomorrow or in the afternoon or the evening, I will bring, I will bring my, my computer and my uhh laptop, you can see [...] a thin section in a picture that's pictures of black sand. I think you can see with the loop as well, with the magnifier. So the whole thing is kind of in play but not in sequence. [...], de-calcified uhh again, which means some water was circulating, the [...] was [...], during the winter, the rainy season, everything was moved around. But you know, moved around. So the, probably, for example, this area, kind of [...]. I [see] a few pockets that resemble more ashy remains. Of course we don't see any more ashes because they have been dissolved away. Actually what you see under the microscope is just sand grains surrounded by [...] made of very fine charcoaled dust, dust charcoal. That's why you don't find, I guess, charcoal inside, probably few bits.\
**Basil:** Yeah, it's nothing. Yeah it's a very very tiny amount.\
**Andreas:** Yeah, I mean okay, it's like putting a fire down on the sand. You know, the sand is something that moves, always, around. Even people when we're trampling it, you know animals, you know [...]. Sadly, nothing would survive, [...] so much not in a [...] but would end up in dust, something like that.\
**Alfred:** Oh well.\
**Andreas:** But still, it's [held up] in place, and made on the, on the material that is just below. So they are, let's say, kind of the same, umm, story.\
**Basil:** Excellent.\
**Alfred:** That's good. Yeah.\
**Andreas:** I mean you can date, I guess the date of both events will not agree. The accumulation of the sand below and the fireplaces on top, they might be about the same age, more or less. I mean, if you are lucky and you [...] you can separate these two events, it would be nice but I think it's, it wouldn't be very [...].\
**Alfred:** [something about carbonized remains]\
**Basil:** We have a few carbonized remains. And we, we just took another 167 litres of flotation so our, we have our archaeobotanist coming through next week.\
**Andreas:** Did you say carbonized or carbonated?\
**Alfred:** Carbonized.\
**Andreas:** Yeah, then of course.\
**Alfred:** But I mean--\
**Andreas:** It is, there's no doubt about it.\
**Alfred:** Yeah.\
**Andreas:** Actually yeah, ok I forgot. There's quite a few burnt bone inside but are reduced in the size of sand. Let's say less than a half a millimetre, but they are burnt. Again, because you know, they are so [can't hear because of the sieve nearby], they've degraded in that small sizes.\
**Basil:** Well, that's the only bone we have from the site so far.\
**Andreas:** I can show you under the mic, I mean they are tiny like, you know, sand grains. And they are burned too.\
**Basil:** I wonder if we could do anything further with that.\
**Andreas:** Other than dating, I don't think, what else? Yeah. Yeah, I think more or less, you can't do more.\
**Basil:** So what--\
**Andreas:** Ahh, I mean, ok, in theory, some more fancy biochemical analysis? I don't know, I don't know if these things have survived. But why not? There have been, lately, some umm biochemical analyses on these kinds of stuff. Right, and you know\
**Alfred:** Lipids?\
**Andreas:** Yeah I don't know, lipids or whatever, maybe it's different, maybe not lipids. You can say whether they were burning plant, or what of plant possibly. I'm not, I'm not sure if all lipids is fat.\
**Alfred:** [...]\
**Andreas:** Well, this kind of analysis, I mean the tools are [...] or ICP, I don't even know. [...]. You want to try [...] you could end up doing it, but I have seen people doing it with palaeolithic [...] see if it works.\
**Basil:** Well we were gonna try it, we're gonna take some sample for aDNA for our, for lack of--\
**Andreas:** No, I think that's absolutely right. I know some people from [an archaeological project] in Spain have done this kind of stuff.

##### A26 {#sec-A26}
**Basil:** It's, I mean, yeah. Umm, now, for a very, you know, for decades, there have been accepted means of scientifically representing the archaeological record, umm to act as evidential bases for your claims. It's understood, that you know, it's impractical for every single interested archaeologist to come to see your site, to see your material. You could be in Australia and the site could be in Peru, umm and so, without that tactile, immediate relationship with the evidence basis that somebody's uhh excavated, there are ways of representing it through photography and line illustration. Umm, that always used to seem to be enough, but it seems like again, it comes down to this contentious nature of our site. The fact that we are, we allegedly have such an early site where such early sites are not meant to be, I'm starting to discover that some of what used to be the accepted means of, accepted ehh evidential umm bases, don't seem to be good enough for everyone. And so it's been very important to have people like Denise come and see this stuff in the flesh. Yes, she's seen the drawing, yes, she's seen the photograph, but for her to see it first hand, handle it, pick it up, query it, umm look at, look at assemblages, as opposed to cherry picked illustrated pieces, has been fundamental to convince her that we really have what we say we have. Ditto Jack. So I think, you know, because I still hear through the grapevine people, you know, muttering, that oh you know, maybe it's this, maybe it's that, you know. And my colleagues over in [the neighbouring region], I mean, what's interesting is that, you know, my colleagues in [that region], Richard and Bruce, they were the first guys to find the Palaeolithic stuff. Denise doesn't believe in that material, so other people do not believe in that material, even though they've done the scientific representation, they drawings and whatever, umm—\
**Zack:** has she handled it?\
**Basil:** I— she's been there, she's been to the site. I don't know if she's handled the material because the material I think was in [another city].\
**Zack:** Do you think that if she were to handle it like she did at [your project] it would, her opinion would change?\
**Basil:** Well I worry that the fact that she's been there and she had a tour of the field, and that's... They have a problem because they work with quartz. Quartz, having just studied some of the material, umm of Richard's Mesolithic site, it's really difficult. Umm, I just studied the material, and I hope I was consistent in my inconsistencies, but like I worry about some of the site. Was I really seeing what I wanted to see? So umm, the visitation of these scholars... Now, there's scholars and there's scholars. The very fact that, you know, to an extent we just tell everybody else bugger off, we don't need you to come anymore, because we're gonna say "see Denise, pers. comm." Denise is gonna go off and tell other people that what she's seen, she believes in, and that's gonna be good enough as a stamp of approval for a lot of people. So that, that's a different, that's—

##### A27 {#sec-A27}
**Zack:** Yeah. So back to the work on [this project], how do you see your work contributing to the overall aims, and if you have a conception of what the overall are...\
**Jolene:** A lot hahaha well they're only dealing with all of the material that's excavated and giving our impressions for the reports. So that literally sets up the basics of how we see, the site.\
**Agatha:** There are no bones, there are no shells\
**Jolene:** How we see it as human activity\
**Zack:** There's a lot of pressure, then\
**Jolene:** So, yes. Of course. So ummm there's lots of pressure but it's also very rewarding when we get the confirmation from the outside.\
**Agatha:** Like we did today\
**Jolene:** It hurts when we don't hahahaha so

##### A28 {#sec-A28}
**Basil:** It's, I mean, yeah. Umm, now, for a very, you know, for decades, there have been accepted means of scientifically representing the archaeological record, umm to act as evidential bases for your claims. It's understood, that you know, it's impractical for every single interested archaeologist to come to see your site, to see your material. You could be in Australia and the site could be in Peru, umm and so, without that tactile, immediate relationship with the evidence basis that somebody's uhh excavated, there are ways of representing it through photography and line illustration. Umm, that always used to seem to be enough, but it seems like again, it comes down to this contentious nature of our site. The fact that we are, we allegedly have such an early site where such early sites are not meant to be, I'm starting to discover that some of what used to be the accepted means of, accepted ehh evidential umm bases, don't seem to be good enough for everyone. And so it's been very important to have people like Denise come and see this stuff in the flesh. Yes, she's seen the drawing, yes, she's seen the photograph, but for her to see it first hand, handle it, pick it up, query it, umm look at, look at assemblages, as opposed to cherry picked illustrated pieces, has been fundamental to convince her that we really have what we say we have. Ditto Jack. So I think, you know, because I still hear through the grapevine people, you know, muttering, that oh you know, maybe it's this, maybe it's that, you know. And my colleagues over in [the neighbouring region], I mean, what's interesting is that, you know, my colleagues in [that region], Richard and Bruce, they were the first guys to find the Palaeolithic stuff. Denise doesn't believe in that material, so other people do not believe in that material, even though they've done the scientific representation, they drawings and whatever, umm—\
**Zack:** has she handled it?\
**Basil:** I— she's been there, she's been to the site. I don't know if she's handled the material because the material I think was in [another city].\
**Zack:** Do you think that if she were to handle it like she did at [your project] it would, her opinion would change?\
**Basil:** Well I worry that the fact that she's been there and she had a tour of the field, and that's... They have a problem because they work with quartz. Quartz, having just studied some of the material, umm of Richard's Mesolithic site, it's really difficult. Umm, I just studied the material, and I hope I was consistent in my inconsistencies, but like I worry about some of the site. Was I really seeing what I wanted to see? So umm, the visitation of these scholars... Now, there's scholars and there's scholars. The very fact that, you know, to an extent we just tell everybody else bugger off, we don't need you to come anymore, because we're gonna say"`see Denise, pers. comm." Denise is gonna go off and tell other people that what she's seen, she believes in, and that's gonna be good enough as a stamp of approval for a lot of people. So that, that's a different, that's—

##### A29 {#sec-A29}
**Basil:** So the superstar material that Lauren was excavating, that we thought was Levallois blade cores, she disagreed. She thinks the material is fabulous, she's never seen this material before in [this region], she thinks it's Aurignation and looks much more like what you would find in France. She's blown away. She's blown away by--\
**Zack:** But it's still Middle Pal?\
**Basil:** Very early Middle Pal. But, we had shown her our superstar pieces. This is where it—\
**Zack:** I was in the trench that first day when we, and I was like cores, wow, tons of them.\
**Basil:** I mean that stuff is— but we had shown her some of our superstar pieces from the survey, like here's a Levallois point, classic thing. But she's like hmm, it's just one piece. Haha you know, it's just like, A, she's not exactly ship's been gone, but she has very high standards.\
**Zack:** So is she sticking with, is she saying that M. Pal was a thing though?\
**Basil:** She was like, so she was looking at these, these little bits and pieces, and like, well, the stuff, you know, we showed her a whole bunch of stuff, it's like, we think this is Levallois, she's like no, it's this. And then we show her some stuff from the survey and it's like, hmm it's one piece and it could be, but it's just one piece, that's not really enough. And then finally we showed her the material, Jolene showed her material from [trench], Alice's new trench, and she's like yes, this is Middle Palaeolithic.\
**Zack:** Ah, okay.

##### A30 {#sec-A30}
**Basil:** Denise came and looked at the stuff and she said: oh, 90\% of this material, you should just take it back to the site. And I was like oh, that's a very liberating statement. So, it's like, yeah. Because, because it's a umm, a quarry site, we've just got stupid amounts of stuff. You know, the amount of techno-typologically diagnostic material is relatively low, and particularly with regard to actually finished, modified tools, is very low. So like, you know, 99\% of our stuff is like un-diagnostic material, apart from it's diagnostic, but you can say this is Upper Palaeolithic. But like most of this stuff if rolled down a hill, it's mixed and blah and whatever. So yeah, we might be able to say that these flakes are Upper Palaeolithic, but actually the end products span the Aurignation to the Gravettian, so this particular flake, we just, there's nothing you can do with it. Is it worth actually saying that there is a... So I think what we can do, but we have to have this conversation out loud with each other, can we justify, like, so you know, one of the contexts I dug, we had 36 bags this big coming out of one context. Now, there might be a very good argument to make, but we need to make this argument out loud to each other and write it down to see if it makes sense and whether we can defend it, whereby of those 36 bags, we're just gonna take one bag and record level 2 all of it as a sample, and then we're gonna rapidly go through the other 35 bags to make sure that there isn't a hand axe in it, take anything sexy out of it, in case we want to draw them, and then the contents of those 35 bags, we put it into the car and we take back to the site. And we do that with every single context we've dug.

##### A31 {#sec-A31}
**Zack:** It's a different kind of engagement than a collaborator though.\
**Basil:** Yes. And uhh, and the rhetoric for me is not going to be so much for investment—\
**Zack:** It's gonna be an arms length—\
**Basil:** Yeah, it's gonna be, in this case, it's like a tactile veracity.

##### A32 {#sec-A32}
**Basil:** But like in terms of the visitor thing, to go back to that, umm, yes, you, having visitors is partly profile raising for the site, community engagement and community creation and networking, uhh we also brought Denise over in part because we wanted to impress her, but also we wanted her critical input and we were kind of, you know, Jolene and I can't publish all of this. We weren't necessarily looking for her to come in to publish with us, because she's a very strong character and I think she might overwhelm us, but we were sort of hoping to maybe get suggestions from her as to who else we could bring in, say like a postdoc or a—

## Case B
##### B1 {#sec-B1}
**Logan:** (from a distance) Hey, Chris! We're ready for pictures and points, uhh to close out both those units.\
**Chris:** Ok! Everybody is. So I have to do photos here, here, here and there hehe\
**Logan:** (joking) I think I'm more important!

##### B2 {#sec-B2}
**Liz:** And then if you can just take one point there, and one point right in the middle, umm that's all we need.\
**Oliver:** Ok.\
**Liz:** And then you're free to start digging and I'll help you out in a minute.\
...\
**Chris:** So what are we doing?\
**Oliver:** We're taking points.\
**Liz:** Just one where you dug.\
**Oliver:** Here?\
**Liz:** Yep, yep. One in there, and then one over there is fine, somewhere in the middle.\
...\
**Chris:** It's excavation unit [redacted ID]?\
**Liz:** Yeah. Closing.\
**Chris:** Alright.

##### B3 {#sec-B3}
**Zack:** hahaha. Umm, so uhh, I guess uhh maybe we'll move onto some questions about, you know, workflows that occur throughout the project. What kinds of, I mean I have to play a little bit ignorant here, so what kinds of material does the project collect? And uhh how are these materials collected? How are they processed and prepared?\
**Rufus:** So just archeo-- you're talking about archaeological--\
**Zack:** Yeah, I mean any, I mean I feel like, because I can see that, but I want to see your perspective on that.\
**Rufus:** Sure. So with the excavation we umm approached that in kind of the new world setting in that we have total collection of pottery, uhh total collection of worked lithics, umm total collection--\
**Greg:** Do you need anything? I'm gonna go downstairs really quick.\
**Rufus:** Umm no, thanks.\
**Greg:** Okay.\
**Rufus:** Uhh so total collection of pottery, umm total collection of any archaeological material coming out of the ground, we collect that. Umm starting next year, we are going to do a palaeo-ethno-botanical kind of approach to things. Uhh with that whole endeavour then, it's once we're, which you've experienced here in that middle trench, we've had inside structure materials, and we're working with uhh a colleague of mine, [redacted], umm back at BU, he has his own palaeoethnobotany lab, so over the, uhh over this next couple of months or so when we're finished in the field in preparation for next year, we'll get the sampling strategy umm because we want to have a robust quantitative approach to the collection of those palaeoethnobotatical remains. Umm the flotation and things like that. So total collection of pottery, and we're gonna do the botanical stuff, umm total collection of any other material. Now once that material leaves the field, obviously it's recorded in a very systematic way. As you're aware, it's tied to the stratigraphic unit itself. Anything of note found in situ is also given a special find number, that becomes a special find, and it's inventoried separately, after the processing is done. Once all the material goes in, ceramics, they're all washed. Umm faunal material is not washed umm. Uhh obviously any metals, we have quite a bit of metals, none of that stuff is washed. The ceramics, once they're washed, that's something that then they are uhh analyzed using a uhh SUIR form, so stratigraphic unit inventory recording form. What that then does for us is we count every shard, we weigh every shard, and then we batch it up by ceramic ware. Anything within that is that is highly diagnostic or useful umm in the interpretation or dating of the site, we take that stuff to the side and inventory that stuff as well. And so that, then the rest of that material, having been quantified then gets bagged, gets put back in the bag, and that goes into storage. Uhh the inventory stuff, then there's a whole new level of recording when there's an inventory catalogue sheet.\
**Zack:** This is for the diagnostics?\
**Rufus:** Exactly. So the inventory catalogue sheets are then taken and number of, a whole new layer of of information is gathered from that. You know, basic weights, thicknesses, umm heights if there are umm, what type of material it is, any type of publications from comparanda that we can bring in. Then that material then becomes the basis for the publication of the catalogue. That, with the generic quantitative information that we pulled from that other material.\
**Zack:** From the non-diagnostic material.\
**Rufus:** From the non-diagnostic, yep.

##### B4 {#sec-B4}
**Zack:** What's, are there anything that's exclusively Chris?\
**Rufus:** Umm so Chris is uhh, so Chris is at [redacted university name] and he's bringing students over this year.\
**Zack:** Right.\
**Rufus:** So he's responsible for that educational component this year. Next year, Logan and I at [redacted university name] will have our own field school as well. Umm so we'll bring out around ten students, and then uhh, and at that point Logan will be responsible for that educational component. Chris will maintain his control of his educational for [redacted university name] students. There will be a lot of overlap [unclear]. But uhh--\
**Zack:** He's gonna be expanding the project, I guess.\
**Rufus:** Yeah, a little bit bigger. And we'll wander around the same trenches, around two or three, but then having delegated groups for pottery washing, switching out that with excavation.

##### B5 {#sec-B5}
In the warehouse now, with Liz, Vanessa, Chris and Lisa. Liz, Vanessa and Chris are organizing the washed ceramics, trying to make other work easier later on. Also, by bagging the pottery that is sitting out on trays, the trays can be put to use by pottery washers. They seem to also be going through a first pass of the material, noting things that stick out from the rest, and also re-bagging stray shell or other kinds of finds that do not belong with the pottery.

##### B6 {#sec-B6}
**Zack:** Do you think that specialists might need some different kinds of, like do they be putting in requests for specific things?\
**Rufus:** So our, no, our faunal person never asked for stuff, but with the the botany stuff--\
**Zack:** Because they provide their own forms, and the templates or whatever, you don't have to...\
**Rufus:** Yeah. They give us a full report, and we then take that report and rework it as part of our department of antiquities report and as part of our publications.

##### B7 {#sec-B7}
**Greg:** So here I have different tables, and I'm normalizing the database. So instead of just creating one table with all the data, I'm creating multiple tables and developing umm foreign keys and relationships, and the primary keys and things like that. So the umm tables I created is area, umm just umm, and I did that because even though it's [the site], we can use umm the area, if he decides to have another site, we can just use the same database. And it can easily add just another another to there. So this isn't umm order but the ones that we use, so the stratigraphic unit holds all the metadata from the forms, so this form here, it's going to hold most all of this except for features and photographs and drawings. So it's going to be a separate table, because we have many, like, one to many. So it's easier, that's what normalizing the database is. It's easier to create this in a separate table, and then it link it to the main table. So then you don't have repeated data, you don't have to keep typing the same stuff in, umm that's, so that's why we're doing the, breaking those out. But most of this stuff, and finds is also going to be another one, because we'll have multiple umm things, and keeping it separate is easier to query that table and link it to whatever you need to. So we'll go back here. Umm so there's the [unclear] and the photographs and drawings tables that go along with the stratigraphic unit table. And the finds table right there, number of bags. So the next one's ceramics, which is going to be this one right here, so it's going to have this data like in one to many, and it's going to link to the stratigraphic unit. So if you need to create a stratigraphic unit you can find out which number you want, and you can say okay, I need all red umm chronotypes of KWCH. So you can query that from this and it's going to find the SU and it's going to find all the, that, those items. So then we have the catalogue, which is going to be this form, which is going to combine the data, the arte-- the SU and the ceramic number, and then they can fill in this data for the catalogue item. Let me go back here. Umm so those are the, I think I covered them all, excavation unit, I just broke that out into its separate table, uhh to keep it umm normalized.\
**Zack:** Yeah.\
**Greg:** So I created all the fields, I created the umm, let's go into one of 'em. Go to the structure. So here you can see umm the ceramic ID, umm it's tied there, SU is a foreign key. So SU is going to tie to the SU table.\
**Zack:** Yeah.\
**Greg:** So that's what the tables look like. And if you look at the others, they're similar. Umm. So here's the catalogue number, you have the ceramic ID number, umm labels, scan, photo, and all this information, umm. That's going to tie to that. So, oh wait, I need to put the SU field in here too. Umm so that's that stuff. Where I'm at now is created the forms. So I'm creating an input form where you can put the data into the database, where you'll go you'll say enter new, there would be a main page, say enter new items, enter new EU, area, whatnot.\
**Zack:** Yeah.\
**Greg:** And then they'll go through, his next, and it would update.

##### B8 {#sec-B8}
**Zack:** Yeah. One thing I've also noticed, as someone who does database work, a lot of these technical aspects are hard to claim authorship for.\
**Rufus:** Sure.\
**Zack:** I've had this experience recently where I was a little bit peeved about having done so much work, not having been credited in a publication. I'm wondering if that's something that you see as potentially changing in the field.\
**Rufus:** Maybe I guess from the director... I was in your exact position, I was running databases and GIS and everything, but I was always given the opportunity to, if I wanted it, to publish stuff, always. So with the photo-- the JFA article and all those other articles, I was given the opportunity to do that, provided that I took an active role in that. For for [redacted project name], example, yeah, any report or report [unclear] our department of antiquities publications or whatever, as a trench supervisor student, I was never put on reports. I was never put on those publications. Once it became field director, which is obviously under co-director, I was. And I was given opportunities to take, to be a lead on these things. I understood that from their perspective that they are bringing over people like trench supervisors, bringing them over, paying their way, room and board, all that stuff, and they had a specific task to do. When they did that task, that information is then absorbed into the project. If they went above and beyond or wanted to take an active role in something, there was opportunities to do that.\
**Zack:** Specifically regarding that, so I I've been trying to find ways of like representing my work, like digital work, which is often like very specific to a specific locus or specific context of work, right. So how did, like it's like, so how do you share this, this collation of data, [unclear] learned a lot, you know these skills that other people don't have, you share that information, that's the sort of thing that I've been struggling with. As these sorts of things become more pervasive, how do you think these are going to be handled?\
**Rufus:** Yeah, I don't know.\
**Zack:** That's a strange question, I haven't really thought through that.\
**Rufus:** Yeah. And I don't know how they would change necessarily. Because on a project director side, this is a 365 day a year deal where you're always writing grants or writing publications, thinking about the project, game planning for next season, getting resources together. And there's a tremendous investment in that. Versus, say, a trench supervisor that's rolling in for three weeks writing the report and then handing it in. That level of contribution wouldn't necessarily equate to an authorship on a peer reviewed publication. And granted, I was that person--\
**Zack:** I'm not trying to pass judgement, I'm just trying to get your perspective.\
**Rufus:** And that would be my perspective I guess. Yeah. If a graduate student or the, I don't really see undergraduates in that particular position. But if that trench supervisor is like, hey, if it, in my instance, if I had somebody come up to me who was a trench supervisor and say, you know, I'm really interested in this thing, I would foster that interest. They could take that on. And that's something that we can authorship on give an the publication. For the creation of a report, no, because what the person is putting in that report is discussions that I had with them. Umm, they're working within a rigid framework of report format style that I gave to them. And it's more of a, it becomes more of a job than an academic slash scholarly contribution. So that's kind of where I see. But, granted again, I was, I was in a trench supervisor position in that exact same scenario, and I guess I never really gave it a thought because I knew that, you know, the sling bullets here, I was, that's something that I was in. Like hey, I'm interested interested in this. really And then they're like, all right, well, go ahead. And they didn't even want their names on it. I was able to publish it all on my own. And so, I am keen to provide opportunities like that for people. But yeah, when it comes down to that all-important peer reviewed publication, having three names on it is very different than having 15 names on it.

##### B9 {#sec-B9}
**Zack:** Would you, but is there more room, like so, the specialists are not as much involved in that process of synthesizing for that, then. You just take the key conclusions and...\
**Rufus:** I take the conclusions, so if I was doing it, I would take the conclusions and I'd work them into the overarching argument.\
**Zack:** Yes, can you just explain the overall process to me, maybe make it more clear. Yeah.\
**Rufus:** Yeah, exactly.\
**Zack:** Yeah. No, I mean...\
**Rufus:** Oh, you're asking me to do that now? Okay. So the overall process being alright, department of antiquity report, whatever specialist report comes in, that's immediately appended verbatim into the final report, with on their name it. When it comes time to actually do a peer reviewed publication, there's a lead author. That lead author has access to that document that they can cut, paste, amend, bring in, rework, whatever they want to do, including those specialist reports. Once that document is then complete, the other co-director gets it to read it over to make their changes. Once that's done, that then goes to the specialist to look over their stuff, to make sure something wasn't misconstrued or whatever. They will then fix, amend as necessary. Then the primary author goes through it all over again. As far as pictures and images go. Those are then created, and then those who made a contribution to the paper, they are listed as authors.

##### B10 {#sec-B10}
Yesterday also saw the initiation of excavation of a pit by the east baulk. It was initially explained to me as possibly being a rubbish pit due to the fact that it is situated around another small east-west wall midway through the north-south wall. As it was being excavated, a bunch of large pottery fragments were recovered, as well as a large long bone, which was of particular concern due to the possibility of it being human. Some speculation was made regarding what animals it might belong to, but no experienced zooarchaeologist was present who could give a definitive interpretation. Chris took some photos with a scale bar and sent them to a colleague who might be able to offer his input from afar. He took the photos using his smart phone, and presumably emailed them to his colleague. I guess we might hear back at some point later today, due to the time zone difference, and his colleague's presumed location in the United States (this being an American-led project). I just overheard Chris talking with his students about the pit, and it seems that the notion of its specialness is beginning to wear off. Its location underlying the wall, however, might still be a loose thread that will need to be explained. Yesterday it was Liz who seemed most perplexed by this aspect of the pit, due to the fact that it does not conform to typical robber pits.
