---
title: Brainstorm
description: Ideas and notes for the data-tech-poli-arch paper.
date: last-modified
---

- On data management as management
- On the distribution of materials within a project among specialists, and how it neatly aligns with database models
- Sampling strategies as a means of controlling the objects, while also reliant on strict distribution of labour
- And implicit recognition that this is not enough: need to bring in consultants to share "being there" perspectives

---

- The rejected JEP abstract has some good language I can borrow.

- explosion paper
  - About the explosion and integration of specialist work.
  - How this work relies on both robust and relaxed means of communication and control.
  - Division of the site
  - Sampling strategies
  - Integrating and aligning perspectives
  - Informal consultation

- See also the excerpt from the draft Information Matters paper, on the role of fieldworkers in preparing samples for lithics specialists to review

- Some bits from roles-agency paper, scaffolding paper

- project and data management paper seems like something that got broken apart into various other drafts

---

About systems of control --- over behaviour, materials and information.
About the utility of these control mechanisms, the apprehensions surrounding it, and healthy vs unhealthy modes of control.


Need to emphasize the political aspects somehow.
Make it more about commoning, role-relations, creative versus automaton forms of agency, and on being used and genericized, who gets to have context recognized?
Extractivist mentality of computer applications, those who thought they were "safe" from genericization are in fact not.

Lead into future project (with Piraye) that investigates who compiles, collates, integrates and standardizes, and the values and tensions that underlie these processes.

The connector is that compilation, collation, integration and standardization happens at all stages of archaeological research, inclduding within projects (which is the topic of the paper).
The things that unify these "scales" of integration are the concern with agency, the apprehension and coping strategies involved, the recognition of flaws or taking data at face value, and "healthy" anxieties that introduce doubt to the formal modes of analysis.

So the paper may be structured as a series of interactions that (a) integrate data through mechanisms of control, countered by (b) recognitions of the limits of those mechanisms.
And then highlight how future work (with Piraye) will do similar analysis on a scale not covered in my dissertation, specifically regarding the work of open data aggregators, which does involve a fundamental shift in perspective (more tech influence, greater confidence in data's validity (by virtue of having undergone peer-review), dilemmas regarding unsavoury uses of data (including AI, cliometrics, pseudoscience, non-archaeological applications, industrial applications etc)).

