---
description: Notes from before / during the workshop.
date: last-modified
---

## Reflections on my own paper

::: {.callout-note}
I wrote this section to get around some writer's block.
I felt very trapped by my abstract submission, so this was a way to reconcile what I wanted to say with what I had already committed.
I think these were originally created in an untracked file on November 25.
:::

The paper should adapt to be more about the re-framing archaeological data management as commons-managament.
Which occurs both within and among projects.
Internally, there is structure to dictate who and how people can contribute and extract.
And externally there is pressure to ensure that the findings are presented in a way that is amenable to being properly read and understood.

The database helps structure these relationships, gives them solid substance by assigning roles, relationships, and commitments.
Sometimes, these scaffolds truly shape how archaeologists relate with each other (application of database logic in sampling and finds processing, relational tables mapping onto specialist domains, lack of substantive communication among specialists), and sometimes archaeologists find ways around them (through consultants who are not accountable to the project and its systems of control).

The goal is to reveal the intertwined nature of data management and people management.
And that by rendering relationships as mere technical processes, we codify relatively fixed collaborative commitments.
However, even still, archaeologists and the character of archaeological data (which can not fit any mold) resist these codified relationships.
But who gets to break these molds? Who gets to claim context-dependency?

Increasingly, even project directors (previously kings of their own projects) are subsumed as generic data points.
Refer in agreement with Catapoti's paper regarding the extractive element of open data.
I observed in some of my work how fieldworkers struck a bargain with project directors, to offload their creative agency to those who have a bigger picture perspective.
Now project directors are asked to do the same thing in service of data science.
The rules of the commons are shifting yet again, as we redefine who can contribute and in what ways, as either generic process or as creative agent.

There is some hope: promoting purposeful, collaborative data sharing, driven by pre-existing collaborative relationships.
People who re-use data truly want to connect in a collaborative sense, and the systems we have set up are insufficient to handle that need.
But there are some great success stories in purposeful and community-driven data sharing initiatives that warrant further exploration.

---

Zafeiriadis' initial presentation was a great overview of the intention of the workshop, and threaded together the very diverse set of papers.
Additionally, he brought up Joe Roe's 2019 blog post concerning how we define or draw boundaries around digital / computational archaeology.

---

Catapoti & Vavouranakis

Brief historical overview of the post-processual theory landscape, and its evolution.
Acknowledgement that these things did not really change day-to-day practice all that much.
As this was occurring, a big division emerged between theory and empirical practice.
Highlighted how much of the work in digital archaeology is acknowledgement of how we do digital archaeology, rather than its actual application.

Includes typologies as a form of block-boxing.

Notion of the "glass box", borrowed from Huggett.
Opening spaces for multivocal interpretation.

Draws attention to a crisis of archaeological identity.
Are we managers and custodians of technical systems?
How do we re-assert the centrality of archaeological inquiry into our workflows?

Discussion really focused on black boxes, etc, and whether data has agency
Stobiecka asked about whether there's value in other disciplinary perspectives, raises digital memory studies as influential in her own work.

---

Indgjerd & Uleberg

Promoting the benefits of properly cleaning and archiving data.
The emergence of small, purposeful uses of AI.
Intra-project data-sharing, involving getting data from prior excavations available for current/ongoing fieldwork.

---

Foka

Mentioned her new book in Cambridge Core Elements book on critical takes on AI, "AI and Image".
Also mentioned Digital reparatory approaches to ai, in response to discussion about digital colonialism by Stobiecka.

---

Kalaycı

Which archaeological tasks are (seemingly) repetitive?
About automation, and whether things could be automated, and what that would entail.
Discussion was very in-depth, concerning what it means to have agency, to be embodied, to create or be embedded in a system of control.
Not really in those words, but in my own conceptual framing, at least.
